name: Build and Deploy Unity StandaloneWindows64

on:
  schedule:
     - cron: "50 * * * *"  # Change time / frequency of build
  workflow_dispatch:

# Will cancel workflow 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    outputs:
      artifact-name: ${{ steps.set-artifact-name.outputs.name }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows64-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-StandaloneWindows64-
            Library-
      
      - name: Build Unity StandaloneWindows64
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          targetPlatform: StandaloneWindows64
          buildsPath: builds
        
      - name: Debug Output Structure
        run: find builds/ -type f | sort
      
      - name: Get Current Date
        id: get-current-date
        run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT
      
      - name: Set Artifact Name
        id: set-artifact-name
        run: echo "name=${{ vars.BUILD_PROJECT_NAME }}-${{ steps.get-current-date.outputs.date }}" >> $GITHUB_OUTPUT

      - name: Upload StandaloneWindows64 Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact-name.outputs.name }}
          path: builds/StandaloneWindows64
          retention-days: 7
  
  deploy:
    name: Deploy to Github Repository
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ./${{ needs.build.outputs.artifact-name }}
          run-id: ${{ github.run_id }}
      
      - name: Zip Build
        run: zip -r ${{ needs.build.outputs.artifact-name }}.zip ./${{ needs.build.outputs.artifact-name }}

      - name: Clone Build Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.BUILD_REPOSITORY }}
          ref: main
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          path: ./build-repo
          lfs: true
      
      - name: Move Build into Repo
        run: cp -rf ./${{ needs.build.outputs.artifact-name }}.zip ./build-repo

      - name: Set git config
        run: |
          cd ./build-repo
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Push Build to Repo
        run: |
          cd ./build-repo
          git add .
          git commit -m "Add New Build"
          git push origin main





